<x-app-layout>
    <div class="d-flex flex-wrap justify-content-between align-items-start gap-3 mb-4"><div><a href="{{ route('provas.index') }}" class="text-decoration-none small"><i class="bi bi-arrow-left me-1"></i>Voltar para provas</a><h1 class="h3 fw-bold mt-3 mb-1">{{ $prova->nome }}</h1><p class="text-muted-custom mb-0">Edite os dados, questões e gabarito desta avaliação.</p></div><span class="badge badge-soft px-3 py-2">{{ $prova->questoes->count() }} questões cadastradas</span></div>
    @if(session('success'))<div class="alert alert-success border-0 shadow-sm">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="alert alert-danger border-0 shadow-sm"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    <div class="row g-4"><div class="col-lg-4"><div class="card-soft p-4 mb-4"><h2 class="h5 fw-bold mb-3">Dados da prova</h2><form method="POST" action="{{ route('provas.update', $prova) }}">@csrf @method('PUT')<label class="form-label fw-semibold">Nome</label><input name="nome" class="form-control mb-3" value="{{ old('nome', $prova->nome) }}" required><label class="form-label fw-semibold">Descrição</label><textarea name="descricao" rows="4" class="form-control mb-3">{{ old('descricao', $prova->descricao) }}</textarea><button class="btn btn-primary w-100">Salvar dados</button></form></div><div class="card-soft p-4"><h2 class="h5 fw-bold">Gabarito atual</h2><p class="small text-muted-custom">Atualizado automaticamente a partir das questões.</p><div class="d-flex flex-wrap gap-2">@forelse($prova->questoes as $q)<span class="badge bg-light text-dark border px-3 py-2">Q{{ $q->numero }} <strong class="text-primary">{{ $q->resposta_correta }}</strong></span>@empty<span class="text-muted">Nenhuma questão ainda.</span>@endforelse</div></div></div>
    <div class="col-lg-8"><div class="card-soft p-4 mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><div><h2 class="h5 fw-bold mb-1">Adicionar questão</h2><p class="small text-muted-custom mb-0">Informe o enunciado, cinco alternativas e a resposta correta.</p></div></div><form method="POST" action="{{ route('questoes.store', $prova) }}">@csrf @include('provas.partials.questao-form', ['questao' => null])<button class="btn btn-primary"><i class="bi bi-plus-lg me-2"></i>Adicionar questão</button></form></div>
    @foreach($prova->questoes as $questao)<div class="card-soft p-4 mb-3"><div class="d-flex justify-content-between align-items-start mb-3"><div class="d-flex gap-3"><span class="question-number">{{ $questao->numero }}</span><div><h3 class="h6 fw-bold mb-1">Questão {{ $questao->numero }}</h3><div class="small text-muted-custom">Gabarito: <strong class="text-success">{{ $questao->resposta_correta }}</strong></div></div></div><form method="POST" action="{{ route('questoes.destroy', $questao) }}" onsubmit="return confirm('Remover esta questão?')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger"><i class="bi bi-trash"></i></button></form></div><form method="POST" action="{{ route('questoes.update', $questao) }}">@csrf @method('PUT') @include('provas.partials.questao-form', ['questao' => $questao])<button class="btn btn-sm btn-light mt-2">Salvar questão</button></form></div>@endforeach
    </div></div>
</x-app-layout>
